# Generated by Django 4.0.10 on 2024-05-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inp_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('summary', models.TextField()),
                ('skills', models.TextField()),
                ('exprience', models.TextField()),
                ('education', models.TextField()),
            ],
        ),
    ]
