# Generated by Django 4.0.10 on 2024-05-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inp_data',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
